language: node_js
node_js:
  - v11
  - v10
  - v9
  - v8
cache:
  directories:
    -node_modules
before_install:
  - npm install -g typescript
install:
  - npm install
script:
  - npm run build
  - npm run test
